### ISSUE TITLE
Implement User Registration and Personal Organization Creation

### ISSUE THREAD

**Issue by nataliaskarl** [ctrl-space-labs/gendox-core#13]
**High level description:**
Develop the user registration process including email confirmation and automatic creation of a personal organization. 
Users should also have the option to register using their Google account.

As a new user,
I want to register an account on the GenDox platform using my email or Google account,
So that I can start using the platform and create projects.

**Acceptance Criteria:**

- User can navigate to the registration page.
- User can register using their email address and password.
- User receives a confirmation email with a link.
- Clicking the confirmation link completes account creation.
- User's account is linked to a personal organization.
- User can register using their Google account.
- After registration, user is logged in and redirected to their personal organization workspace.

**Email Template:**

> Dear [User's Name],
> Welcome to GenDox, your AI-powered data management and project collaboration platform!
> 
> We're excited to have you on board. To complete your registration and start using GenDox, please click the confirmation link below:
> 
> [Confirmation Link]
> 
> By confirming your email, you'll gain access to a wealth of features, including project creation, document management, and intelligent AI agent interactions.
> 
> If you didn't sign up for GenDox or have any questions, please contact our support team at [[support@email.com](mailto:support@email.com)].
> 
> Thank you for choosing GenDox. We look forward to seeing you in action!
> 
> Best regards,
> 
> The GenDox Team
> 

**OPEN POINTS:**
1. Designs to be attached

**Comment by sekasx** [comment]
done
