### ISSUE TITLE
Develop User Role and Permission Management

### ISSUE THREAD

**Issue by nataliaskarl** [ctrl-space-labs/gendox-core#15]
**High-Level Description:** 
Create functionality for Admin and Moderator users to change roles and remove members within an organization. 
Ensure proper handling of self-removal and notifications.

User Story:
As an Admin or Moderator,
I want to manage user roles and permissions within the organization,
So that I can control access and collaboration effectively.

**Acceptance Criteria:**

- Admin/Moderator can navigate to the organization's Members section.
- Admin/Moderator can select a member and change their role.
- System updates the member's role according to the change.
- Admin/Moderator can remove a member from the organization.
- System prompts for confirmation before removing a member.
- Admin/Moderator cannot remove themselves without assigning another Admin/Moderator.
- User is notified of role changes and removals.

**Comment by sekasx** [comment]
Role and permissions associations to be provided by @sekasx or @gyfantidis

**Comment by sekasx** [comment]
Role management has been implemented.
