### ISSUE TITLE
Implement Agent Setup and Configuration - "AI Agent" Settings Tab

### ISSUE THREAD

**Issue by nataliaskarl** [ctrl-space-labs/gendox-core#17]
**High-Level Description:** 
Develop the interface for users to set up AI agent roles, behavior styles, names, descriptions, and technology options. 
Include privacy settings and ensure data integrity.

**User Story:**
As a user managing AI agents,
I want to configure an AI agent's role, behavior style, name, description, and technology options,
So that the AI agent is tailored to the project's needs.

**Acceptance Criteria:**

- User can navigate to the AI agent's settings within a project.
- User chooses a personality for the AI agent from a dropdown (e.g., Creative, Balanced, Precise).
- User can provide a description or guidance for the AI agent, including any additional information.
- User selects the access type for the AI agent: Public or Private.
- User can choose the desired AI LLM from the following list, while having available a short description of each one of them:

| LLM                   | Short Description                                          | Why Choose It?                                           |
|-----------------------|------------------------------------------------------------|----------------------------------------------------------|
| GPT-3                 | Advanced Language Model                                   | Choose GPT-3 for versatile natural language processing. Its large scale and pre-trained capabilities make it suitable for various tasks, from chatbots to content generation.                                      |
| GPT-4                 | Cutting-Edge AI Language Model                            | Opt for GPT-4 when you need state-of-the-art natural language understanding and generation. It offers improved performance and accuracy, making it ideal for complex language tasks. |
| Facebook LLaMa 2      | Robust Multilingual Language Model                        | Select Facebook LLaMa 2 for multilingual support and robustness. It excels in cross-language applications, making it valuable for global communication and data analysis.           |

- Changes to AI agent settings are saved and reflected.

**Comment by sekasx** [comment]
Available LLMs:
- GPT-3
- GPT-4
- Facebook LLaMa 2 (Coming soon)

**Comment by nataliaskarl** [comment]
> Available LLMs:
> 
> * GPT-3
> * GPT-4
> * Facebook LLaMa 2 (Coming soon)

Updated description

**Comment by sekasx** [comment]
Better naming is needed but the functionality is there. As of now the supported models are:
- GPT-3.5-turbo
- GPT-4-turbo
- GPT-4-o
- Cohere
- LLaMa 3 8B with Groq
- LLaMa 3 70B with Groq
- **ANY** self-hosted LLM customer wants to run using Ollama
