### ISSUE TITLE
Implement Document Upload Functionality

### ISSUE THREAD

**Issue by nataliaskarl** [ctrl-space-labs/gendox-core#18]
**High-Level Description:**
Develop the ability for users to upload various types of documents into a project on the GenDox platform.

**User Story:**
As a project contributor,
I want to upload multiple types of documents into my project,
So that I can use them to train the AI agent.

**Acceptance Criteria:**

- User can navigate to the project's homepage.
- User can click on the "Upload Documents" button.
- A pop-up window allows users to drag and drop or select files.
- System validates supported document formats (.txt, Markdown, RST, Simple PDFs).
- In case the user tries to upload any other format, they should be informed that: "Sorry, the selected file format is not supported for document upload. Please make sure your document is in one of the following formats: .txt, Markdown (.md), ReStructuredText (.rst), or a simple PDF."
- System uploads the selected documents to the project.
- User receives a confirmation message upon successful upload.

**Open Point:** UX Designs to be added

### UX

https://www.figma.com/file/WZQtbGbaYXQRLHAYKrtflQ/Product-Wireframes?type=design&node-id=1983-1458&mode=design&t=EI5SZTUOjKlHCswh-4

https://www.figma.com/file/WZQtbGbaYXQRLHAYKrtflQ/Product-Wireframes?type=design&node-id=1983-1500&mode=design&t=EI5SZTUOjKlHCswh-4

**Comment by sekasx** [comment]
At the first phase, Documents can be only text files like .txt, Markdown, RST, Simple PDFs

**Comment by nataliaskarl** [comment]
> At the first phase, Documents can be only text files like .txt, Markdown, RST, Simple PDFs

Updated description
