### ISSUE TITLE
 Implement Document Creation from Template

### ISSUE THREAD

**Issue by nataliaskarl** [ctrl-space-labs/gendox-core#20]
**High-Level Description:** 
Develop the functionality for users to create new content documents using existing content templates.

**User Story:**
As a content creator,
I want to generate a new document from an existing content template,
So that I can efficiently structure my content.

**Acceptance Criteria:**

- User can navigate to the project's content management section.
- User can click on the "New Document" button.
- User selects an existing content template.
- System generates a new content document using the selected template.
- User can fill in the document fields and save the new document.
- User receives the following confirmation message upon successful document creation: "Success! You've created a new document from the selected template. You can now start filling in the document fields and organizing your content."

**Comment by sekasx** [comment]
out-of-scope
closing this, we'll create a new one when the time comes
