### ISSUE TITLE
Access Recent Documents and Templates per Project

### ISSUE THREAD

**Issue by nataliaskarl** [ctrl-space-labs/gendox-core#21]
**High-Level Description:** 
Allow the users to conveniently access their recently used documents and templates within each project's workspace.

**User Story:**
As a user managing multiple projects,
I want to easily access the most recent documents and templates within each project's workspace,
So that I can efficiently continue working on my projects without searching through extensive lists.

**Acceptance Criteria:**

- User can navigate to a project's workspace from the left-hand menu
- Project workspace displays a **"Recent Documents"** section.
- The section lists document titles and short descriptions for recently accessed documents.
- At least five (adjustable) of the most recently accessed documents are displayed, along with the related date & time that were last modified. 
- The user is able to do a left scroll in order to view all the documents or to expand all the documents while covering the majority of the screen
- In case there are no Recent Documents, the user should have available the following message: "No Recent Documents Available"
- Project workspace displays a **"Recent Templates"** section.
- The section lists template names for recently accessed content templates.
- At least five (adjustable) of the most recently accessed templates are displayed, along with the related date & time that were last modified. 
- Each document/template entry in the recent lists includes a clickable title.
- Clicking on a document/template title opens the respective document or template for viewing/editing.
- The date in every document should be: "X hours ago/days/weeks".
- Each document should include the editor's name
- If a user hasn't accessed any recent documents/templates, the "Recent Documents" and "Recent Templates" sections include the message: "No Recent Documents Available"
- The lists are specific to the selected project; accessing a different project updates the lists accordingly.
- Recent documents/templates lists are sorted based on access timestamp, with the most recent appearing at the top.

### UX
https://www.figma.com/file/WZQtbGbaYXQRLHAYKrtflQ/Product-Wireframes?type=design&node-id=1983-1374&mode=design&t=EI5SZTUOjKlHCswh-4

**Comment by konstantinaleousi** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcGlvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--647f8f85e9aa5a67583065183ddb55f8baf8bae7/image.png)

**Comment by nataliaskarl** [comment]
1. The date should be: "X hours ago/days/weeks". 
2. "My" should be removed from the headers 
3. Screenshot should be updated

**Comment by sekasx** [comment]
- Document Templates are out of scope for 2024. 
- Left scrolling has been replaced with vertical scrolling
All others has been implemented
