### ISSUE TITLE
Limited Access to Recent Documents and Templates per Project

### ISSUE THREAD

**Issue by nataliaskarl** [ctrl-space-labs/gendox-core#22]
**High-Level Description:** 
Develop a feature that allows users with access to a specific project to conveniently access their recently used documents and templates within that project's workspace, while ensuring restricted access to other projects within the organization.

**User Story:**
As a user with access to a specific project,
I want to easily access the most recent documents and templates within that project's workspace,
While ensuring that I don't have access to the recent documents and templates of other projects within the organization.

**Comment by sekasx** [comment]
implemented
