### ISSUE TITLE
Enhance UI and Functionality of Login Page Buttons

### ISSUE THREAD

**Issue by gyfantidis** [ctrl-space-labs/gendox-core#232]
### Description:
This task is focused on redesigning the user interface of the app's login page and updating the functionality of the 'Forgot Password' and 'Register' buttons. The objective is to ensure a seamless and visually appealing user experience that aligns with our latest design guidelines, while also ensuring these buttons perform their respective actions efficiently.

- Forgot Passwrod
- Register

**Comment by gyfantidis** [comment]
@sekasx [https://codepen.io/ggyfantidis/pen/dyEPreE](url)

**Comment by sekasx** [comment]
This is done!
