### ISSUE TITLE
Update Sidebar for Enhanced Usability in Compact Mode

### ISSUE THREAD

**Issue by gyfantidis** [ctrl-space-labs/gendox-core#238]
### Description:
This task involves updating the sidebar's user interface to enhance its functionality and appearance when toggled to a smaller, compact mode. Changes will include resizing and redesigning buttons for better usability, modifying the home menu for accessibility, and creating a new custom list feature to improve user interaction.

**Comment by sekasx** [comment]
Several updated implemented, closing this.
