### ISSUE TITLE
Managing Organization Settings

### ISSUE THREAD

**Issue by nataliaskarl** [ctrl-space-labs/gendox-core#24]
**High-Level Description:** 
Develop organization settings functionality that allows organization administrators to manage various aspects, including switching organizations, creating new organizations, deleting organizations and inviting members.

**User Stories and Acceptance Criteria:**

**1. Switch Organization**

**User Story:**
As a user managing multiple organizations,
I want to easily switch between different organizations I'm a part of,
So that I can access and manage their respective settings.

**Acceptance Criteria:**
- User can navigate to the organization's "Settings" area from the top navigation related icon. 
- A dropdown menu or similar UI element allows users to select and switch between different organizations they belong to.

**2. Create New Organization**

User Story:
As a user with administrative privileges,
I want to create a new organization,
So that I can set up a separate workspace for a new project or team.

Acceptance Criteria:

- User can navigate to the organization's "Settings" area from the top navigation.
- User clicks on a "Create New Organization" button.
- User provides necessary details like the organization name and description.
- The system creates a new organization and adds the user as the administrator.

**3. Delete Organization**

User Story:
As an organization administrator,
I want to delete an organization that is no longer needed,
So that I can declutter and manage my organizations effectively.

Acceptance Criteria:

- User can navigate to the organization's "Settings" area from the top navigation.
- User selects the organization they wish to delete.
- A "Delete Organization" button is available.
- The confirmation prompt asks the user to confirm the deletion: "Are you sure you want to delete this organization?
- This action will permanently delete the organization, including all its projects and associated data. This cannot be undone." (Cancel/Delete)
- Upon confirmation, the system deletes the organization, its projects, and all associated data.

**Open Points:**
1. UX Designs should be updated accordingly.

**Comment by sekasx** [comment]
To split this into `Project Settings` and `Organization Setting`.Similar UI. Different fields

**Comment by sekasx** [comment]
@nataliaskarl project settings/configuration will go to #16 or #17

**Comment by nataliaskarl** [comment]
> @nataliaskarl project settings/configuration will go to #16 or #17

Updated description in order to include only the Organization handling (create/update/delete).

**Comment by sekasx** [comment]
Users can add in an organization also:
- logo image
- Private LLM API Keys
