### ISSUE TITLE
Resetting Password on Gendox Platform

### ISSUE THREAD

**Issue by nataliaskarl** [ctrl-space-labs/gendox-core#25]
**High-Level Description:** 
Develop a feature that enables users to reset their password in case they forget it, ensuring secure access to their Gendox account.

**User Story:**
As a user who has forgotten my Gendox account password,
I want to be able to reset my password securely,
So that I can regain access to my account.

**Acceptance Criteria:**

- User navigates to the Gendox login page.
- User clicks on the "Forgot Password?" link provided on the login page.
- User is redirected to the password reset page.
- User is prompted to enter the email address associated with their Gendox account.
- After entering the email address, user clicks on the "Submit" button.
- System validates the email address and sends a password reset link to the user's email.
- User receives an email containing the password reset link.
- User clicks on the password reset link, which directs them to a password reset page.
- User is prompted to enter a new password and confirm it.
- After entering and confirming the new password, user clicks on the "Reset Password" button.
- System validates the new password and updates the user's account with the new password.
- User receives a confirmation message indicating that the password has been successfully reset.
- User can now use the new password to log in to their Gendox account.

**Email Template:**

> Subject: Gendox Password Reset Instructions
> 
> Message:
> Dear [User's Name],
> 
> We received a request to reset your Gendox account password. To ensure the security of your account, please follow the instructions below:
> 
> Click the following link to reset your password:
> [Password Reset Link](https://chat.openai.com/c/password_reset_link_here)
> 
> You will be directed to a page where you can enter your new password.
> 1. Enter your new password and confirm it.
> 2. Click the "Reset Password" button.
> 3. Once you've completed these steps, your password will be updated, and you'll be able to log in to your Gendox account with your new password.
> 
> If you didn't request this password reset, please ignore this email. Your account security is important to us, and no changes have been made to your account.
> 
> If you have any questions or need further assistance, please contact our support team at [[support@email.com](mailto:support@email.com)].
> 
> Thank you for using Gendox!
> 
> Best regards,
> The Gendox Team

**Comment by sekasx** [comment]
Done!
