### ISSUE TITLE
Implement Invite/Remove New Members to a Project

### ISSUE THREAD

**Issue by gyfantidis** [ctrl-space-labs/gendox-core#265]
### Description:
We need to implement a feature that allows administrators to invite new members to the project. This feature should include a user-friendly interface for sending invitations and managing the invitation process.

## Behavior

- user clicks invite user
- a form opens:
  - type the email to invite (autocomplete with existing org users)
  - select the organization's role
 - clicks `Send`

The user can also remove someone from the Project Members.

**Comment by sekasx** [comment]
In #259 the API has been implemented. This just needs to be used in the Frontend.
The invitation is for **a project** in the organization.
(updating the ticket title)

**Comment by sekasx** [comment]
There are multiple tickets for user invitations...
