### ISSUE TITLE
As a Backend Dev I want to implement Documents API

### ISSUE THREAD

**Issue by sekasx** [ctrl-space-labs/gendox-core#28]
## Description

Document API should be available under `/documents`
The supported operations are:
- **GET `/documents/{id}`** -> Get by id

- **GET `/documents`** -> Get by Criteria. The Criteria are:
  - TBD
  
- POST `/documents` -> Create Document
  - Store the sections and their metadata also
  
- PUT `/documents/{id}` -> Update document
  - Store the sections. The metadata should be updated only if documentTemplate is empty/null
  - Organization can't be changed 

- DELETE `/documents/{id}` -> Delete document by id

- POST `/documents/upload` -> Upload Multiple Documents
  - Document should be able to be uploaded to Local Disk or S3. The code should be the same, and only change the configuration, with NO aws library. To achieve this ResourceLoader can be used. 
  - A document section should be created for each file,
  - Different strategies should be supported, and configurable from the DB (using Strategy Pattern or something similar)

**Comment by sekasx** [comment]
@gyfantidis merge this ticket with #37

**Comment by gyfantidis** [comment]
Duplicate with ticket #37
