### ISSUE TITLE
As a Backend Developer, I want to Implement Permissions in  Projects, Organizations and Documents Controllers

### ISSUE THREAD

**Issue by gyfantidis** [ctrl-space-labs/gendox-core#30]
# Controllers To-Do List

## Project Controller
- `GET /projects/{id}` - Get Project by ID.
 - [ ] Implement `@PreAuthorize` with `OP_READ_PROJECT` authority for the requested project ID .
- `GET /projects` - Get All Projects. 
 - [ ] Implement `@PreAuthorize` for appropriate permissions.
- `POST /projects` - Create a New Project.
 - [ ] Implement `@PreAuthorize` with `OP_CREATE_PROJECT` for the requested organization.
- `PUT /projects/{id}` - Update a Project.
-  [ ] Implement `@PreAuthorize` with `OP_UPDATE_PROJECT` for the requested organization.
-  [ ] Ensure the user is a member of the project.
- `DELETE /projects/{id}` - Delete a Project.
 - [ ] Implement `@PreAuthorize` with `OP_DELETE_PROJECT` for the requested organization.
 - [ ] Ensure the user is a member of the project.
- `GET /projects/{id}/users` - Get users by project
 - [ ] Implement `@PreAuthorize` for appropriate permissions.
 - [ ] Validate that the role level is not higher than the user's role level for this project.
- `Post /projects/{projectId}/users/{userId}` - create user in the project
 - [ ] Implement `@PreAuthorize` with `OP_CREATE_PROJECT` for the requested organization.
- `Delete /projects/{projectId}/users/{userId}` - delete user from the project
 - [ ] Implement `@PreAuthorize` with `OP_DELETE_PROJECT` for the requested organization.
 - [ ] Ensure the user is a member of the project.

## Organization Controller
- `GET /organizations/{id}` - Get organization by ID.
 - [ ] Implement `@PreAuthorize` with `OP_READ_ORGANIZATION` authority for the requested  organization ID .
- `GET /organizations` - Get All Organizations. 
 - [ ] Implement `@PreAuthorize` for appropriate permissions.
- `POST /organizations` - Create a New Organization.
 - [ ] Implement `@PreAuthorize` with `OP_CREATE_ORGANIZATION` for the requested organization.
- `PUT /organizations/{id}` - Update a organization.
-  [ ] Implement `@PreAuthorize` with `OP_UPDATE_ORGANIZATION` for the requested organization.
-  [ ] Ensure the user is a member of the organizations.
- `DELETE /organizations/{id}` - Delete a organization.
 - [ ] Implement `@PreAuthorize` with `OP_DELETE_ORGANIZATION` for the requested organization.
 - [ ] Ensure the user is a member of the organization.
- `GET /organizations/{id}/users` - Get users by organization
 - [ ] Implement `@PreAuthorize` for appropriate permissions.
 - [ ] Validate that the role level is not higher than the user's role level for this organization.
- `Post /organizations/{id}/users` - create user in the organization
 - [ ] Implement `@PreAuthorize` with `OP_CREATE_ORGANIZATION` for the requested organization.

## Documents Controller
- `GET /documents/{id}` - Get document by ID.
 - [ ] Implement `@PreAuthorize` with `OP_READ_DOCUMENT` authority for the requested  document ID .
- `GET /documents` - Get All documents. 
 - [ ] Implement `@PreAuthorize` for appropriate permissions.
- `POST /documents` - Create a New document.
 - [ ] Implement `@PreAuthorize` with `OP_CREATE_DOCUMENT` for the requested organization.
- `PUT /documents/{id}` - Update a document.
-  [ ] Implement `@PreAuthorize` with `OP_UPDATE_DOCUMENT` for the requested organization.
-  [ ] Ensure the user is a member of the organizations.
- `DELETE /documents/{id}` - Delete a document.
 - [ ] Implement `@PreAuthorize` with `OP_DELETE_DOCUMENT` for the requested organization.
 - [ ] Ensure the user is a member of the organization.
- `GET /documents/{id}/users` - Get users by document
 - [ ] Implement `@PreAuthorize` for appropriate permissions.
 - [ ] Validate that the role level is not higher than the user's role level for this organization.
- `Post /documents/{id}/users` - create user in the document
 - [ ] Implement `@PreAuthorize` with `OP_CREATE_DOCUMENT` for the requested organization.

**Comment by sekasx** [comment]
Done
