### ISSUE TITLE
Add `createdBy` and `updatedBy` column in all tables

### ISSUE THREAD

**Issue by sekasx** [ctrl-space-labs/gendox-core#34]
## Description 

Columns `createdBy` and `updatedBy` are typically used to Audit table changes. Spring has a library to make the easier. The same library handles and the `createAt` and `updatedAt` columns.
Tables to add the columns:
- projects
- project_agent
- organizations
- document_template
- document_section_metadata
- document_instance
- document_instance_sections

All Java Entities/Services need to be updated appropriately.
The Entity fields will be just `String UUID` (not the whole User Entity)

### Spring Documentation:
https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#auditing.basics

**Comment by gyfantidis** [comment]
Have been completed
-gendox_core.projects Table
 -add created_by column
 -add updated_by column
-gendox_core.projects_agent Table
 -add created_by column
 -add updated_by column
-gendox_core.organizations Table
 -add created_by column
 -add updated_by column
-gendox_core.document_template Table
 -add created_by column
 -add updated_by column
-gendox_core.document_section_metadata Table
 -add created_by column
 -add updated_by column
-gendox_core.document_instance Table
 -add remote_url column 
 -add created_by column
 -add updated_by column
-gendox_core.document_instance_section Table
 -delete remote_url column
 -add created_by column
 -add updated_by column

-add file V20230911_123210__Core_Schema_initial_tables.sql

**Comment by gyfantidis** [comment]
Have been completed
- gendox_core.projects Table
  - add created_by column
  - add updated_by column
- gendox_core.projects_agent Table
  - add created_by column
  - add updated_by column
- gendox_core.organizations Table
  - add created_by column
  - add updated_by column
- gendox_core.document_template Table
  - add created_by column
  - add updated_by column
- gendox_core.document_section_metadata Table
  - add created_by column
  - add updated_by column
- gendox_core.document_instance Table
  - add remote_url column 
  - add created_by column
  - add updated_by column
- gendox_core.document_instance_section Table
  - delete remote_url column
  - add created_by column
  - add updated_by column

- add file V20230911_123210__Core_Schema_initial_tables.sql

**Comment by gyfantidis** [comment]
Have been completed
- gendox_core.projects Table
  - add created_by column
  - add updated_by column
- gendox_core.projects_agent Table
  - add created_by column
  - add updated_by column
- gendox_core.organizations Table
  - add created_by column
  - add updated_by column
- gendox_core.document_template Table
  - add created_by column
  - add updated_by column
- gendox_core.document_section_metadata Table
  - add created_by column
  - add updated_by column
- gendox_core.document_instance Table
  - add remote_url column 
  - add created_by column
  - add updated_by column
- gendox_core.document_instance_section Table
  - delete remote_url column
  - add created_by column
  - add updated_by column

- add file V20230911_123210__Core_Schema_initial_tables.sql
