### ISSUE TITLE
Implement Inactivity Timeout Pop-Up for Enhanced Security

### ISSUE THREAD

**Issue by nataliaskarl** [ctrl-space-labs/gendox-core#39]
**High-Level Description:**
Implement a popup message to notify users when they have been inactive for more than 15 minutes, enhancing security and ensuring the protection of user data.

**User Story:**
As a GenDox user,
I want to receive a popup message if I am inactive for more than 15 minutes,
So that my data and account remain secure, and I can resume my work safely.

**Acceptance Criteria:**
- The system detects user inactivity for 15 minutes.
- A popup message appears on the user's screen.
- The message provides a brief warning about inactivity and its potential security risks.
- Users are given the option to dismiss the message or log back in.
- If the user dismisses the message, it disappears, and the user can continue using GenDox.
- If the user chooses to log back in, they are redirected to the login page.
- User activity is defined as any interaction with the GenDox platform, such as clicks, keystrokes, or mouse movements.

**Security Alert:**

> Your session has been inactive for more than 15 minutes. To protect your data and ensure the security of your account, please choose one of the following options:
> Dismiss: If you're still here, click 'Dismiss' to continue working.
> Log In: If you're no longer active, click 'Log In' to sign back into your account.
> For your security, if there is no action within the next 15 minutes, you will be automatically logged out.

**User Interaction:**

- If the user dismisses the popup message, it should not reappear until they have been inactive for another 15 minutes.
- If the user logs back in, they should be taken to the login page and prompted to re-enter their credentials.

**Open Points:**
UX Designs

**Comment by sekasx** [comment]
Not implemented as a pop-up.
users just logout as per normal web experience.
