### ISSUE TITLE
Create Project Gendox Documentation Tasks

### ISSUE THREAD

**Issue by gyfantidis** [ctrl-space-labs/gendox-core#43]
# Project Gendox Documentation Tasks

## README

- [x] Provide an introduction to Gendox.
- [x] Explain how to run Gendox locally.
- [x] Mention where to find the rest of the documentation (e.g., GitHub Wiki).

## How to Use the API

- [ ] Create a high-level overview of the API.
- [ ] Describe the endpoints and its functionality.
- [ ] List the available AI models for projects.
- [ ] Document the parameters for each API endpoints.
- [ ] Specify which parameters are mandatory.

## Developer's Guide

- [ ] Explain the basic components of the application.
- [ ] Provide an overview of how to start developing with Gendox.
- [ ] Describe the database model.
- [ ] Document the Java entities related to the database.
- [ ] Explain how and why to use services in Gendox.
- [ ] Document the purpose and logic of converters.
- [ ] Explain how to use QueryDSL for complex queries.
- [ ] Document the purpose of custom validation annotations (e.g., @AtLeastOne).
- [ ] Describe the JWT structure.
- [ ] Document which parts of the application require authorization checks.

**Comment by sekasx** [comment]
@gyfantidis are all those documents done?
