### ISSUE TITLE
As a backend developer, I want to optimize sections and embeddings for faster app training

### ISSUE THREAD

**Issue by gyfantidis** [ctrl-space-labs/gendox-core#62]
# Task Description

**Description:**
As part of our ongoing effort to enhance app performance, the goal of this task is to optimize the process of generating section embeddings during app training. Currently, this process is causing performance bottlenecks, leading to longer training times. Your task is to identify and implement improvements to make the section embeddings generation significantly faster without sacrificing accuracy.

**Comment by sekasx** [comment]
several thinks implemented during the past year. This is not applicable anymore. Although several things need to be improved, this ticket is not mentioning something specific.

Closing..
